
import type { DrugCategory } from '../types';

export const drugCategories: DrugCategory[] = [
    { id: 'antiespasmodicos', name: 'Antiespasmódicos' },
    { id: 'inhaladores', name: 'Inhaladores Nasales' },
    { id: 'vitaminas', name: 'Vitaminas/Factor Vitamínico' },
    { id: 'antiparasitarios', name: 'Antiparasitarios' },
    { id: 'antigripales', name: 'Antigripales' },
    { id: 'antibioticos', name: 'Antibióticos' },
    { id: 'jarabes', name: 'Jarabes Antitusivos/Expectorantes' },
    { id: 'antialergicos', name: 'Antialérgicos' },
    { id: 'colirios', name: 'Colirios' },
    { id: 'analgesicos', name: 'Analgésicos/Antiinflamatorios' },
    { id: 'antidiarreicos', name: 'Antidiarreicos' },
    { id: 'ansioliticos', name: 'Ansiolíticos' },
    { id: 'antidepresivos', name: 'Antidepresivos' },
    { id: 'antipireticos', name: 'Antipiréticos' },
    { id: 'antiepilepticos', name: 'Antiepilépticos' },
    { id: 'antipsicoticos', name: 'Antipsicóticos' },
    { id: 'hipnoticos', name: 'Hipnótico/Sedante' },
    { id: 'anestesicos', name: 'Anestésicos' },
    { id: 'antiacidos', name: 'Antiácidos/Protectores Gástricos' },
    { id: 'diureticos', name: 'Diuréticos' },
    { id: 'antidiabeticos', name: 'Antidiabéticos' },
    { id: 'antianemicos', name: 'Anti Anémicos' },
    { id: 'laxantes', name: 'Laxantes' },
    { id: 'antiemeticos', name: 'Antieméticos' },
    { id: 'antifungicos', name: 'Antifúngicos/Antimicóticos' },
    { id: 'antihemorragicos', name: 'Antihemorrágicos' },
    { id: 'antihistaminicos', name: 'Antihistamínicos' },
    { id: 'antisepticos', name: 'Antisépticos/Desinfectantes' },
    { id: 'tuberculosis', name: 'Tratamiento Tuberculosis' },
    { id: 'antianginoso', name: 'Anti Anginoso' },
    { id: 'antitrombotico', name: 'Antitrombótico/Trombolítico' },
    { id: 'antiagregante', name: 'Antiagregante Plaquetario/Antivirales' },
    { id: 'corticoides', name: 'Corticoides Tópicos/Sistémicos' },
    { id: 'hipolipemiante', name: 'Hipolipemiante' },
    { id: 'relajantemuscular', name: 'Relajante Muscular' },
    { id: 'terapiatiroidea', name: 'Terapia Tiroidea' },
    { id: 'antiasmatico', name: 'Antiasmático/Broncodilatador' },
    { id: 'parto', name: 'Inductor/Inhibidor del Parto' },
    { id: 'anticonceptivos', name: 'Anticonceptivos' },
    { id: 'cardiotonicos', name: 'Cardiotónicos' },
    { id: 'antiarritmicos', name: 'Antiarrítmicos' },
    { id: 'antihipertensivos', name: 'Antihipertensivos' },
    { id: 'inmunosupresores', name: 'Inmunosupresores' },
    { id: 'betabloqueadores', name: 'Betabloqueadores' },
];
